// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Impeto.Exchange.Web.ArduinoAPI.Models;
using Newtonsoft.Json.Linq;

namespace Impeto.Exchange.Web.ArduinoAPI.Models
{
    public static partial class SalaDeReuniaoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<SalaDeReuniao> DeserializeJson(JToken inputObject)
        {
            IList<SalaDeReuniao> deserializedObject = new List<SalaDeReuniao>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                SalaDeReuniao salaDeReuniao = new SalaDeReuniao();
                salaDeReuniao.DeserializeJson(iListValue);
                deserializedObject.Add(salaDeReuniao);
            }
            return deserializedObject;
        }
    }
}
