/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 17/04/2017 20:10:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 17/04/2017 20:10:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoles](
	[Id] [nvarchar](128) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 17/04/2017 20:10:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](128) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.AspNetUserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 17/04/2017 20:10:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserLogins](
	[LoginProvider] [nvarchar](128) NOT NULL,
	[ProviderKey] [nvarchar](128) NOT NULL,
	[UserId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 17/04/2017 20:10:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserRoles](
	[UserId] [nvarchar](128) NOT NULL,
	[RoleId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 17/04/2017 20:10:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUsers](
	[Id] [nvarchar](128) NOT NULL,
	[TXT_NOME] [nvarchar](max) NULL,
	[TXT_FIRST_DEVICE] [nvarchar](max) NULL,
	[COD_CLIENTE] [int] NOT NULL,
	[Email] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEndDateUtc] [datetime] NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[TB_CLIENTE]    Script Date: 17/04/2017 20:10:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_CLIENTE](
	[COD_CLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[TXT_NOME] [nvarchar](100) NOT NULL,
	[TXT_SMTP] [nvarchar](100) NOT NULL,
	[TXT_SENHA] [nvarchar](100) NOT NULL,
	[TXT_TOKEN] [nvarchar](200) NULL,
	[TXT_FIRST_DEVICE] [nvarchar](12) NOT NULL,
	[DAT_CADASTRO] [datetime] NOT NULL,
	[TXT_USER_IDENTITY] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.TB_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[COD_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[TB_DISPOSITIVO]    Script Date: 17/04/2017 20:10:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_DISPOSITIVO](
	[COD_DISPOSITIVO] [int] IDENTITY(1,1) NOT NULL,
	[TXT_SERIAL] [nvarchar](12) NOT NULL,
	[TXT_NOME] [nvarchar](100) NULL,
	[TXT_SMTP] [nvarchar](100) NULL,
	[TXT_MAC] [nvarchar](12) NULL,
	[TXT_TOKEN] [nvarchar](100) NULL,
	[DAT_ATIVACAO] [datetime] NOT NULL,
	[IND_ATIVO] [bit] NOT NULL,
	[COD_CLIENTE] [int] NULL,
	[TXT_TIMEZONE] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_dbo.TB_DISPOSITIVO] PRIMARY KEY CLUSTERED 
(
	[COD_DISPOSITIVO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[TB_EXCHANGE_AVAIABILITY]    Script Date: 17/04/2017 20:10:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_EXCHANGE_AVAIABILITY](
	[COD_EXCHANGE_AVAIABILITY] [int] IDENTITY(1,1) NOT NULL,
	[TXT_NAME] [nvarchar](max) NULL,
	[TIP_MEETING_ATTENDEE] [int] NOT NULL,
	[TXT_MESSAGE] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.TB_EXCHANGE_AVAIABILITY] PRIMARY KEY CLUSTERED 
(
	[COD_EXCHANGE_AVAIABILITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS]    Script Date: 17/04/2017 20:10:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS](
	[COD_EXCHANGE_AVAIABILITY_STATUS] [int] IDENTITY(1,1) NOT NULL,
	[COD_EXCHANGE_AVAIABILITY] [int] NOT NULL,
	[COD_STATUS_AVAIABILITY] [int] NOT NULL,
	[DAT_NEXT_MEETING_ROOM_SUG] [datetime] NULL,
	[TXT_MESSAGE] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.TB_EXCHANGE_AVAIABILITY_STATUS] PRIMARY KEY CLUSTERED 
(
	[COD_EXCHANGE_AVAIABILITY_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS_DETAIL]    Script Date: 17/04/2017 20:10:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS_DETAIL](
	[COD_EXCHANGE_AVAIABILITY_STATUS_DETAIL] [int] IDENTITY(1,1) NOT NULL,
	[DAT_INICIO] [datetime] NULL,
	[DAT_FIM] [datetime] NULL,
	[COD_STATUS] [int] NOT NULL,
	[IND_IS_EXCEPTION] [bit] NOT NULL,
	[IND_IS_MEETING] [bit] NOT NULL,
	[IND_IS_PRIVATIVE] [bit] NOT NULL,
	[IND_IS_REMINDER_SET] [bit] NOT NULL,
	[TXT_LOCATION] [nvarchar](max) NULL,
	[TXT_STORE_ID] [nvarchar](max) NULL,
	[IND_SUBJECT] [nvarchar](max) NULL,
	[COD_EXCHANGE_AVAIABILITY_STATUS] [int] NOT NULL,
 CONSTRAINT [PK_dbo.TB_EXCHANGE_AVAIABILITY_STATUS_DETAIL] PRIMARY KEY CLUSTERED 
(
	[COD_EXCHANGE_AVAIABILITY_STATUS_DETAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[TB_DISPOSITIVO]  WITH CHECK ADD  CONSTRAINT [FK_dbo.TB_DISPOSITIVO_dbo.TB_CLIENTE_COD_CLIENTE] FOREIGN KEY([COD_CLIENTE])
REFERENCES [dbo].[TB_CLIENTE] ([COD_CLIENTE])
GO
ALTER TABLE [dbo].[TB_DISPOSITIVO] CHECK CONSTRAINT [FK_dbo.TB_DISPOSITIVO_dbo.TB_CLIENTE_COD_CLIENTE]
GO
ALTER TABLE [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_dbo.TB_EXCHANGE_AVAIABILITY_STATUS_dbo.TB_EXCHANGE_AVAIABILITY_COD_EXCHANGE_AVAIABILITY] FOREIGN KEY([COD_EXCHANGE_AVAIABILITY])
REFERENCES [dbo].[TB_EXCHANGE_AVAIABILITY] ([COD_EXCHANGE_AVAIABILITY])
GO
ALTER TABLE [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS] CHECK CONSTRAINT [FK_dbo.TB_EXCHANGE_AVAIABILITY_STATUS_dbo.TB_EXCHANGE_AVAIABILITY_COD_EXCHANGE_AVAIABILITY]
GO
ALTER TABLE [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_dbo.TB_EXCHANGE_AVAIABILITY_STATUS_DETAIL_dbo.TB_EXCHANGE_AVAIABILITY_STATUS_COD_EXCHANGE_AVAIABILITY_STATUS] FOREIGN KEY([COD_EXCHANGE_AVAIABILITY_STATUS])
REFERENCES [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS] ([COD_EXCHANGE_AVAIABILITY_STATUS])
GO
ALTER TABLE [dbo].[TB_EXCHANGE_AVAIABILITY_STATUS_DETAIL] CHECK CONSTRAINT [FK_dbo.TB_EXCHANGE_AVAIABILITY_STATUS_DETAIL_dbo.TB_EXCHANGE_AVAIABILITY_STATUS_COD_EXCHANGE_AVAIABILITY_STATUS]
GO
