BEGIN TRANSACTION;
CREATE TABLE "TB_PLANO" (
	`COD_PLANO`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`TXT_TITULO`	TEXT,
	`NUM_QUANTIDADE`	INTEGER DEFAULT 0,
	`DAT_INICIO_VIGENCIA`	TEXT DEFAULT CURRENT_TIMESTAMP,
	`DAT_FIM_VIGENCIA`	TEXT,
	`VAL_PRECO`	NUMERIC
);
INSERT INTO `TB_PLANO` (COD_PLANO,TXT_TITULO,NUM_QUANTIDADE,DAT_INICIO_VIGENCIA,DAT_FIM_VIGENCIA,VAL_PRECO) VALUES (1,NULL,0,'2017-02-03 14:23:56',NULL,NULL),
 (2,'Plano DISP10',10,'2017-02-03 14:24:48',NULL,NULL),
 (3,'Plano DISP10',10,'2017-02-03 14:25:16','2017-12-31 23:59:59','2000,00');
CREATE TABLE "TB_DISPOSITIVO" (
	`COD_DISPOSITIVO`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`COD_CLIENTE`	INTEGER NOT NULL,
	`TXT_NOME`	TEXT,
	`TXT_SSID_ID`	TEXT,
	`TXT_SSID_PASS`	TEXT,
	`TXT_MAC`	TEXT UNIQUE,
	`TXT_TOKEN`	TEXT,
	`NUM_TEMPO_FIXO`	INTEGER DEFAULT 60,
	`NUM_TEMPO_EVNT`	INTEGER DEFAULT 60,
	`DAT_ATIVACAO`	TEXT DEFAULT CURRENT_TIMESTAMP,
	`IND_ATIVO`	INTEGER DEFAULT 1,
	FOREIGN KEY(`COD_CLIENTE`) REFERENCES TB_CLIENTE(COD_CLIENTE)
);
INSERT INTO `TB_DISPOSITIVO` (COD_DISPOSITIVO,COD_CLIENTE,TXT_NOME,TXT_SSID_ID,TXT_SSID_PASS,TXT_MAC,TXT_TOKEN,NUM_TEMPO_FIXO,NUM_TEMPO_EVNT,DAT_ATIVACAO,IND_ATIVO) VALUES (1,1,'Dispositivo do Cid','FusionWIFI','senha','00-00-00-00-00-00','cid',60,60,'2017-02-01 01:00:00',1),
 (2,1,'Dispositivo 2','FusionWIFI','senha','00-00-00-00-00-01','cid',60,60,'2017-02-03 14:22:18',0);
CREATE TABLE "TB_CLIENTE" (
	`COD_CLIENTE`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`TXT_NOME`	TEXT UNIQUE,
	`TXT_SMTP`	TEXT,
	`TXT_SENHA`	TEXT,
	`TXT_TOKEN`	TEXT,
	`TXT_TIMEZONE`	TEXT,
	`DAT_CADASTRO`	TEXT DEFAULT CURRENT_TIMESTAMP,
	`COD_PLANO`	INTEGER,
	FOREIGN KEY(`COD_PLANO`) REFERENCES TB_PLANO(COD_PLANO)
);
INSERT INTO `TB_CLIENTE` (COD_CLIENTE,TXT_NOME,TXT_SMTP,TXT_SENHA,TXT_TOKEN,TXT_TIMEZONE,DAT_CADASTRO,COD_PLANO) VALUES (1,'Fusion','contato@avmsistemas.net','senha','cid','E. South America Standard Time','''2017-02-01 01:00:00''',1);
CREATE INDEX `IX_DISPOSITIVO_CLIENTE` ON `TB_DISPOSITIVO` (`COD_DISPOSITIVO` ASC,`COD_CLIENTE` ASC);
CREATE INDEX `IX_CLIENTE_PLANO` ON `TB_CLIENTE` (`COD_CLIENTE` ASC,`COD_PLANO` ASC);
COMMIT;
